# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

logo: "clonos-web-logo.png"
title: Clonos
email: pmfsilvestre@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Clonos is a performant and flexible approach to fault tolerance in 
  distributed stream processing systems based on causal logging which achieves
  high-availability and consistency.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://delftdata.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#url: ""
twitter_username: pmfsilvestre
github_username:  PSilvestre

permalink: pretty

back_to_top: true
back_to_top_text: "Back to top"

favicon.ico: "./favicon.ico"
favicon_ico: "./favicon.ico"

# Build settings
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

color_scheme: clonos
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#

search_enabled: true


aux_links:
  "Clonos on GitHub":
    - "//github.com/delftdata/Clonos"
  "Download the paper":
    - "http://asterios.katsifodimos.com/assets/publications/clonos-sigmod2021.pdf"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

footer_content: "Copyright &copy; 2021-2021 TU Delft - Web Information Systems."

ga_tracking: G-K86Z1TDMWL
ga_tracking_anonymize_ip: true

# TODO collections
